INSERT INTO [dbo].[Game] (
    [RetroGameID]
    ,[ParkID]
    ,[GameType]
    ,[Date]
    ,[GameNumber]
    ,[DayOfWeek]
    ,[StartTime]
    ,[DHUsedFlag]
    ,[DayNightFlag]
    ,[VisitingTeam]
    ,[HomeTeam]
    ,[VisitorStartingPitcher]
    ,[HomeStartingPitcher]
    ,[HomePlateUmpire]
    ,[FirstBaseUmpire]
    ,[SecondBaseUmpire]
    ,[ThirdBaseUmpire]
    ,[LeftFieldUmpire]
    ,[RightFieldUmpire]
    ,[Attendance]
    ,[HowScored]
    ,[PitchesEntered]
    ,[Temperature]
    ,[WindDirection]
    ,[WindSpeed]
    ,[FieldCondition]
    ,[Precipitation]
    ,[Sky]
    ,[TimeOfGame]
    ,[NumberOfInnings]
    ,[VisitorFinalScore]
    ,[HomeFinalScore]
    ,[VisitorHits]
    ,[HomeHits]
    ,[VisitorErrors]
    ,[HomeErrors]
    ,[VisitorLeftOnBase]
    ,[HomeLeftOnBase]
    ,[WinningPitcher]
    ,[LosingPitcher]
    ,[SaveFor]
    ,[GWRBI]
    ,[VisitorBatter1]
    ,[VisitorPosition1]
    ,[VisitorBatter2]
    ,[VisitorPosition2]
    ,[VisitorBatter3]
    ,[VisitorPosition3]
    ,[VisitorBatter4]
    ,[VisitorPosition4]
    ,[VisitorBatter5]
    ,[VisitorPosition5]
    ,[VisitorBatter6]
    ,[VisitorPosition6]
    ,[VisitorBatter7]
    ,[VisitorPosition7]
    ,[VisitorBatter8]
    ,[VisitorPosition8]
    ,[VisitorBatter9]
    ,[VisitorPosition9]
    ,[HomeBatter1]
    ,[HomePosition1]
    ,[HomeBatter2]
    ,[HomePosition2]
    ,[HomeBatter3]
    ,[HomePosition3]
    ,[HomeBatter4]
    ,[HomePosition4]
    ,[HomeBatter5]
    ,[HomePosition5]
    ,[HomeBatter6]
    ,[HomePosition6]
    ,[HomeBatter7]
    ,[HomePosition7]
    ,[HomeBatter8]
    ,[HomePosition8]
    ,[HomeBatter9]
    ,[HomePosition9]
    ,[VisitingFinisher]
    ,[HomeFinisher]
    ,[OfficialScorer]
)
SELECT
    [RetroGameID] = [GameID]
    ,[ParkID] = pk.[ParkID]
    ,[GameType]
    ,[Date] = TRY_CAST(SUBSTRING([GameID], 4, 4) + '-' + SUBSTRING([GameID], 8, 2) + '-' + SUBSTRING([GameID], 10, 2) AS DATE)
    ,[GameNumber]
    ,[DayOfWeek]
    ,[StartTime] =
        CASE
            WHEN LEN([StartTime]) = N'4' THEN SUBSTRING([StartTime], 1, 2) + ':' + SUBSTRING([StartTime], 3, 2)
            WHEN LEN([StartTime]) = N'3' THEN SUBSTRING([StartTime], 1, 1) + ':' + SUBSTRING([StartTime], 2, 2)
            ELSE NULL
        END
    ,[DHUsedFlag] = CASE WHEN [DHUsedFlag] = N'T' THEN 1 ELSE 0 END
    ,[DayNightFlag]
    ,[VisitingTeam]
    ,[HomeTeam]
    ,[VisitorStartingPitcher] = vsp.[PlayerID]
    ,[HomeStartingPitcher] = hsp.[PlayerID]
    ,[HomePlateUmpire] = hpu.[PlayerID]
    ,[FirstBaseUmpire] = fbu.[PlayerID]
    ,[SecondBaseUmpire] = sbu.[PlayerID]
    ,[ThirdBaseUmpire] = tbu.[PlayerID]
    ,[LeftFieldUmpire] = lfu.[PlayerID]
    ,[RightFieldUmpire] = rfu.[PlayerID]
    ,[Attendance]
    ,[HowScored]
    ,[PitchesEntered]
    ,[Temperature]
    ,[WindDirection]
    ,[WindSpeed]
    ,[FieldCondition]
    ,[Precipitation]
    ,[Sky]
    ,[TimeOfGame]
    ,[NumberOfInnings]
    ,[VisitorFinalScore]
    ,[HomeFinalScore]
    ,[VisitorHits]
    ,[HomeHits]
    ,[VisitorErrors]
    ,[HomeErrors]
    ,[VisitorLeftOnBase]
    ,[HomeLeftOnBase]
    ,[WinningPitcher] = win.[PlayerID]
    ,[LosingPitcher] = los.[PlayerID]
    ,[SaveFor] = sav.[PlayerID]
    ,[GWRBI] = gwrbi.[PlayerID]
    ,[VisitorBatter1] = vb1.[PlayerID]
    ,[VisitorPosition1]
    ,[VisitorBatter2] = vb2.[PlayerID]
    ,[VisitorPosition2]
    ,[VisitorBatter3] = vb3.[PlayerID]
    ,[VisitorPosition3]
    ,[VisitorBatter4] = vb4.[PlayerID]
    ,[VisitorPosition4]
    ,[VisitorBatter5] = vb5.[PlayerID]
    ,[VisitorPosition5]
    ,[VisitorBatter6] = vb6.[PlayerID]
    ,[VisitorPosition6]
    ,[VisitorBatter7] = vb7.[PlayerID]
    ,[VisitorPosition7]
    ,[VisitorBatter8] = vb8.[PlayerID]
    ,[VisitorPosition8]
    ,[VisitorBatter9] = vb9.[PlayerID]
    ,[VisitorPosition9]
    ,[HomeBatter1] = hb1.[PlayerID]
    ,[HomePosition1]
    ,[HomeBatter2] = hb2.[PlayerID]
    ,[HomePosition2]
    ,[HomeBatter3] = hb3.[PlayerID]
    ,[HomePosition3]
    ,[HomeBatter4] = hb4.[PlayerID]
    ,[HomePosition4]
    ,[HomeBatter5] = hb5.[PlayerID]
    ,[HomePosition5]
    ,[HomeBatter6] = hb6.[PlayerID]
    ,[HomePosition6]
    ,[HomeBatter7] = hb7.[PlayerID]
    ,[HomePosition7]
    ,[HomeBatter8] = hb8.[PlayerID]
    ,[HomePosition8]
    ,[HomeBatter9] = hb9.[PlayerID]
    ,[HomePosition9]
    ,[VisitingFinisher] = vif.[PlayerID]
    ,[HomeFinisher] = hmf.[PlayerID]
    ,[OfficialScorer] = sco.[PlayerID]
FROM
    [raw].[Game] g
    LEFT JOIN [dbo].[ParkMaster] pk ON g.[GameSite] = pk.[RetroParkID]
    LEFT JOIN [dbo].[PlayerMaster] vsp ON g.[VisitorStartingPitcher] = vsp.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hsp ON g.[HomeStartingPitcher] = hsp.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hpu ON g.[HomePlateUmpire] = hpu.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] fbu ON g.[FirstBaseUmpire] = fbu.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] sbu ON g.[SecondBaseUmpire] = sbu.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] tbu ON g.[ThirdBaseUmpire] = tbu.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] lfu ON g.[LeftFieldUmpire] = lfu.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rfu ON g.[RightFieldUmpire] = rfu.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] win ON g.[WinningPitcher] = win.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] los ON g.[LosingPitcher] = los.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] sav ON g.[SaveFor] = sav.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] gwrbi ON g.[GWRBI] = gwrbi.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb1 ON g.[VisitorBatter1] = vb1.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb2 ON g.[VisitorBatter2] = vb2.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb3 ON g.[VisitorBatter3] = vb3.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb4 ON g.[VisitorBatter4] = vb4.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb5 ON g.[VisitorBatter5] = vb5.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb6 ON g.[VisitorBatter6] = vb6.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb7 ON g.[VisitorBatter7] = vb7.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb8 ON g.[VisitorBatter8] = vb8.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vb9 ON g.[VisitorBatter9] = vb9.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb1 ON g.[HomeBatter1] = hb1.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb2 ON g.[HomeBatter2] = hb2.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb3 ON g.[HomeBatter3] = hb3.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb4 ON g.[HomeBatter4] = hb4.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb5 ON g.[HomeBatter5] = hb5.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb6 ON g.[HomeBatter6] = hb6.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb7 ON g.[HomeBatter7] = hb7.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb8 ON g.[HomeBatter8] = hb8.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hb9 ON g.[HomeBatter9] = hb9.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] vif ON g.[VisitingFinisher] = vif.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] hmf ON g.[HomeFinisher] = hmf.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] sco ON g.[OfficialScorer] = sco.[RetroPlayerID]
ORDER BY
    TRY_CAST(SUBSTRING([GameID], 4, 4) + '-' + SUBSTRING([GameID], 8, 2) + '-' + SUBSTRING([GameID], 10, 2) AS DATE)
    ,g.[GameID]
    ,CONVERT(INT, g.[GameNumber])
