INSERT INTO [dbo].[Event] (
    [GameID]
    ,[EventNum]
    ,[Inning]
    ,[BattingTeam]
    ,[Outs]
    ,[Balls]
    ,[Strikes]
    ,[PitchSequence]
    ,[VisScore]
    ,[HomeScore]
    ,[Batter]
    ,[BatterHand]
    ,[ResBatter]
    ,[ResBatterHand]
    ,[Pitcher]
    ,[PitcherHand]
    ,[ResPitcher]
    ,[ResPitcherHand]
    ,[Catcher]
    ,[FirstBase]
    ,[SecondBase]
    ,[ThirdBase]
    ,[Shortstop]
    ,[LeftField]
    ,[CenterField]
    ,[RightField]
    ,[FirstRunner]
    ,[SecondRunner]
    ,[ThirdRunner]
    ,[EventText]
    ,[LeadoffFlag]
    ,[PinchHitFlag]
    ,[DefensivePosition]
    ,[LineupPosition]
    ,[EventType]
    ,[BatterEventFlag]
    ,[ABFlag]
    ,[HitValue]
    ,[SHFlag]
    ,[SFFlag]
    ,[OutsOnPlay]
    ,[DoublePlayFlag]
    ,[TriplePlayFlag]
    ,[RBIOnPlay]
    ,[WildPitchFlag]
    ,[PassedBallFlag]
    ,[FieldedBy]
    ,[BattedBallType]
    ,[BuntFlag]
    ,[FoulFlag]
    ,[HitLocation]
    ,[NumErrors]
    ,[ErrorPlayer1]
    ,[ErrorType1]
    ,[ErrorPlayer2]
    ,[ErrorType2]
    ,[ErrorPlayer3]
    ,[ErrorType3]
    ,[BatterDest]
    ,[RunnerOn1stDest]
    ,[RunnerOn2ndDest]
    ,[RunnerOn3rdDest]
    ,[PlayOnBatter]
    ,[PlayOnRunnerOn1st]
    ,[PlayOnRunnerOn2nd]
    ,[PlayOnRunnerOn3rd]
    ,[SBForRunnerOn1stFlag]
    ,[SBForRunnerOn2ndFlag]
    ,[SBForRunnerOn3rdFlag]
    ,[CSForRunnerOn1stFlag]
    ,[CSForRunnerOn2ndFlag]
    ,[CSForRunnerOn3rdFlag]
    ,[POForRunnerOn1stFlag]
    ,[POForRunnerOn2ndFlag]
    ,[POForRunnerOn3rdFlag]
    ,[ResponsiblePitcherForRunnerOn1st]
    ,[ResponsiblePitcherForRunnerOn2nd]
    ,[ResponsiblePitcherForRunnerOn3rd]
    ,[NewGameFlag]
    ,[EndGameFlag]
    ,[PinchRunnerOn1st]
    ,[PinchRunnerOn2nd]
    ,[PinchRunnerOn3rd]
    ,[RunnerRemovedForPinchRunnerOn1st]
    ,[RunnerRemovedForPinchRunnerOn1st2nd]
    ,[RunnerRemovedForPinchRunnerOn1st3rd]
    ,[BatterRemovedForPinchHitter]
    ,[PositionOfBatterRemovedForPinchHitter]
    ,[FielderWithFirstPutout]
    ,[FielderWithSecondPutout]
    ,[FielderWithThirdPutout]
    ,[FielderWithFirstAssist]
    ,[FielderWithSecondAssist]
    ,[FielderWithThirdAssist]
    ,[FielderWithFourthAssist]
    ,[FielderWithFifthAssist]
)
SELECT
    g.[GameID]
    ,[EventNum]
    ,[Inning]
    ,[BattingTeam]
    ,[Outs]
    ,[Balls]
    ,[Strikes]
    ,[PitchSequence]
    ,[VisScore]
    ,[HomeScore]
    ,[Batter] = b.[PlayerID]
    ,[BatterHand]
    ,[ResBatter] = rb.[PlayerID]
    ,[ResBatterHand]
    ,[Pitcher] = p.[PlayerID]
    ,[PitcherHand]
    ,[ResPitcher] = rp.[PlayerID]
    ,[ResPitcherHand]
    ,[Catcher] = c.[PlayerID]
    ,[FirstBase] = f.[PlayerID]
    ,[SecondBase] = s.[PlayerID]
    ,[ThirdBase] = t.[PlayerID]
    ,[Shortstop] = ss.[PlayerID]
    ,[LeftField] = lf.[PlayerID]
    ,[CenterField] = cf.[PlayerID]
    ,[RightField] = rf.[PlayerID]
    ,[FirstRunner] = fr.[PlayerID]
    ,[SecondRunner] = sr.[PlayerID]
    ,[ThirdRunner] = tr.[PlayerID]
    ,[EventText]
	,[LeadoffFlag] = CASE WHEN [LeadoffFlag] = 'T' THEN 1 ELSE 0 END
	,[PinchHitFlag] = CASE WHEN [PinchHitFlag] = 'T' THEN 1 ELSE 0 END
    ,[DefensivePosition]
    ,[LineupPosition]
    ,[EventType]
	,[BatterEventFlag] = CASE WHEN [BatterEventFlag] = 'T' THEN 1 ELSE 0 END
	,[ABFlag] = CASE WHEN [ABFlag] = 'T' THEN 1 ELSE 0 END
    ,[HitValue]
	,[SHFlag] = CASE WHEN [SHFlag] = 'T' THEN 1 ELSE 0 END
	,[SFFlag] = CASE WHEN [SFFlag] = 'T' THEN 1 ELSE 0 END
    ,[OutsOnPlay]
	,[DoublePlayFlag] = CASE WHEN [DoublePlayFlag] = 'T' THEN 1 ELSE 0 END
	,[TriplePlayFlag] = CASE WHEN [TriplePlayFlag] = 'T' THEN 1 ELSE 0 END
    ,[RBIOnPlay]
	,[WildPitchFlag] = CASE WHEN [WildPitchFlag] = 'T' THEN 1 ELSE 0 END
	,[PassedBallFlag] = CASE WHEN [PassedBallFlag] = 'T' THEN 1 ELSE 0 END
    ,[FieldedBy]
    ,[BattedBallType]
	,[BuntFlag] = CASE WHEN [BuntFlag] = 'T' THEN 1 ELSE 0 END
	,[FoulFlag] = CASE WHEN [FoulFlag] = 'T' THEN 1 ELSE 0 END
    ,[HitLocation]
    ,[NumErrors]
    ,[ErrorPlayer1]
    ,[ErrorType1]
    ,[ErrorPlayer2]
    ,[ErrorType2]
    ,[ErrorPlayer3]
    ,[ErrorType3]
    ,[BatterDest]
    ,[RunnerOn1stDest]
    ,[RunnerOn2ndDest]
    ,[RunnerOn3rdDest]
    ,[PlayOnBatter]
    ,[PlayOnRunnerOn1st]
    ,[PlayOnRunnerOn2nd]
    ,[PlayOnRunnerOn3rd]
	,[SBForRunnerOn1stFlag] = CASE WHEN [SBForRunnerOn1stFlag] = 'T' THEN 1 ELSE 0 END
	,[SBForRunnerOn2ndFlag] = CASE WHEN [SBForRunnerOn2ndFlag] = 'T' THEN 1 ELSE 0 END
	,[SBForRunnerOn3rdFlag] = CASE WHEN [SBForRunnerOn3rdFlag] = 'T' THEN 1 ELSE 0 END
	,[CSForRunnerOn1stFlag] = CASE WHEN [CSForRunnerOn1stFlag] = 'T' THEN 1 ELSE 0 END
	,[CSForRunnerOn2ndFlag] = CASE WHEN [CSForRunnerOn2ndFlag] = 'T' THEN 1 ELSE 0 END
	,[CSForRunnerOn3rdFlag] = CASE WHEN [CSForRunnerOn3rdFlag] = 'T' THEN 1 ELSE 0 END
	,[POForRunnerOn1stFlag] = CASE WHEN [POForRunnerOn1stFlag] = 'T' THEN 1 ELSE 0 END
	,[POForRunnerOn2ndFlag] = CASE WHEN [POForRunnerOn2ndFlag] = 'T' THEN 1 ELSE 0 END
	,[POForRunnerOn3rdFlag] = CASE WHEN [POForRunnerOn3rdFlag] = 'T' THEN 1 ELSE 0 END
    ,[ResponsiblePitcherForRunnerOn1st] = rpro1.[PlayerID]
    ,[ResponsiblePitcherForRunnerOn2nd] = rpro2.[PlayerID]
    ,[ResponsiblePitcherForRunnerOn3rd] = rpro3.[PlayerID]
	,[NewGameFlag] = CASE WHEN [NewGameFlag] = 'T' THEN 1 ELSE 0 END
	,[EndGameFlag] = CASE WHEN [EndGameFlag] = 'T' THEN 1 ELSE 0 END
	,[PinchRunnerOn1st] = CASE WHEN [PinchRunnerOn1st] = 'T' THEN 1 ELSE 0 END
	,[PinchRunnerOn2nd] = CASE WHEN [PinchRunnerOn2nd] = 'T' THEN 1 ELSE 0 END
	,[PinchRunnerOn3rd] = CASE WHEN [PinchRunnerOn3rd] = 'T' THEN 1 ELSE 0 END
    ,[RunnerRemovedForPinchRunnerOn1st] = rrpro1.[PlayerID]
    ,[RunnerRemovedForPinchRunnerOn1st2nd] = rrpro12.[PlayerID]
    ,[RunnerRemovedForPinchRunnerOn1st3rd] = rrpro13.[PlayerID]
    ,[BatterRemovedForPinchHitter] = brph.[PlayerID]
    ,[PositionOfBatterRemovedForPinchHitter]
    ,[FielderWithFirstPutout]
    ,[FielderWithSecondPutout]
    ,[FielderWithThirdPutout]
    ,[FielderWithFirstAssist]
    ,[FielderWithSecondAssist]
    ,[FielderWithThirdAssist]
    ,[FielderWithFourthAssist]
    ,[FielderWithFifthAssist]
FROM
    [raw].[Event] e
    LEFT JOIN [dbo].[Game] g ON e.[GameID] = g.[RetroGameID]
    LEFT JOIN [dbo].[PlayerMaster] b ON e.[Batter] = b.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rb ON e.[ResBatter] = rb.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] p ON e.[Pitcher] = p.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rp ON e.[ResPitcher] = rp.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] c ON e.[Catcher] = c.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] f ON e.[FirstBase] = f.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] s ON e.[SecondBase] = s.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] t ON e.[ThirdBase] = t.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] ss ON e.[Shortstop] = ss.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] lf ON e.[LeftField] = lf.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] cf ON e.[CenterField] = cf.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rf ON e.[RightField] = rf.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] fr ON e.[FirstRunner] = fr.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] sr ON e.[SecondRunner] = sr.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] tr ON e.[ThirdRunner] = tr.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rpro1 ON e.[ResponsiblePitcherForRunnerOn1st] = rpro1.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rpro2 ON e.[ResponsiblePitcherForRunnerOn2nd] = rpro2.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rpro3 ON e.[ResponsiblePitcherForRunnerOn3rd] = rpro3.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rrpro1 ON e.[RunnerRemovedForPinchRunnerOn1st] = rrpro1.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rrpro12 ON e.[RunnerRemovedForPinchRunnerOn1st2nd] = rrpro12.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] rrpro13 ON e.[RunnerRemovedForPinchRunnerOn1st3rd] = rrpro13.[RetroPlayerID]
    LEFT JOIN [dbo].[PlayerMaster] brph ON e.[BatterRemovedForPinchHitter] = brph.[RetroPlayerID]
ORDER BY
	SUBSTRING(e.[GameID], 4, 4) + '-' + SUBSTRING(e.[GameID], 8, 2) + '-' + SUBSTRING(e.[GameID], 10, 2)
	,e.[GameID]
	,CONVERT(INT, [EventNum])
