USE [Retrosheet]

INSERT INTO [stg].[PlayerMaster]
           ([RetroPlayerID]
           ,[FirstName]
           ,[LastName]
           ,[Nickname]
           ,[Birthdate]
           ,[BirthCity]
           ,[BirthState]
           ,[BirthCountry]
           ,[PlayerDebut]
           ,[PlayerLastGame]
           ,[ManagerDebut]
           ,[ManagerLastGame]
           ,[CoachDebut]
           ,[CoachLastGame]
           ,[UmpDebut]
           ,[UmpLastGame]
           ,[DeathDate]
           ,[DeathCity]
           ,[DeathState]
           ,[DeathCountry]
           ,[Bats]
           ,[Throws]
           ,[Height]
           ,[Weight]
           ,[Cemetery]
           ,[CemeteryCity]
           ,[CemeteryState]
           ,[CemeteryCountry]
           ,[CemeteryNote]
           ,[BirthName]
           ,[NameChg]
           ,[BatChg]
           ,[IsHof])
SELECT DISTINCT
	UPPER([PLAYERID]) AS [RetroPlayerID]
	,[LAST]
	,[FIRST]
	,[NICKNAME]
	,TRY_CAST([BIRTHDATE] AS DATE) AS [BIRTHDATE]
	,[BIRTH_CITY]
	,[BIRTH_STATE]
	,[BIRTH_COUNTRY]
	,TRY_CAST([PLAY_DEBUT] AS DATE) AS [PlayerDebut]
	,TRY_CAST([PLAY_LASTGAME] AS DATE) AS [PlayerLastGame]
	,TRY_CAST([MGR_DEBUT] AS DATE) AS [ManagerDebut]
	,TRY_CAST([MGR_LASTGAME] AS DATE) AS [ManagerLastGame]
	,TRY_CAST([COACH_DEBUT] AS DATE) AS [CoachDebut]
	,TRY_CAST([COACH_LASTGAME] AS DATE) AS [CoachLastGame]
	,TRY_CAST([UMP_DEBUT] AS DATE) AS [UmpDebut]
	,TRY_CAST([UMP_LASTGAME] AS DATE) AS [UmpLastGame]
	,TRY_CAST([DEATHDATE] AS DATE) AS [DeathDate]
	,[DEATH_CITY]
	,[DEATH_STATE]
	,[DEATH_COUNTRY]
	,[BATS]
	,[THROWS]
	,[HEIGHT]
	,REPLACE([WEIGHT], '.0', '') AS Weight
	,[CEMETERY]
	,[CEME_CITY]
	,[CEME_STATE]
	,[CEME_COUNTRY]
	,[CEME_NOTE]
	,[BIRTH_NAME]
	,[NAME_CHG]
	,[BAT_CHG]
	,CASE WHEN [HOF] IS NOT NULL THEN 1 ELSE 0 END AS [IsHof]
FROM
	[raw].[PlayerMaster]
ORDER BY
	[RetroPlayerID]


update a
set
    a.[Birthdate] = b.[Birthdate]
	,a.[PlayerDebut] = b.[PlayerDebut]
	,a.[PlayerLastGame] = b.[PlayerLastGame]
	,a.[ManagerDebut] = b.[ManagerDebut]
	,a.[ManagerLastGame] = b.[ManagerLastGame]
	,a.[CoachDebut] = b.[CoachDebut]
	,a.[CoachLastGame] = b.[CoachLastGame]
	,a.[UmpDebut] = b.[UmpDebut]
	,a.[UmpLastGame] = b.[UmpLastGame]
	,a.[DeathDate] = b.[DeathDate]
    ,a.[dModified] = GETDATE()
from
    dbo.PlayerMaster a
    join stg.PlayerMaster b on a.RetroPlayerID = b.RetroPlayerID


select * from dbo.PlayerMaster
