CREATE TABLE [raw].[ParkMaster]
(
	[ParkID] VARCHAR(500) NOT NULL
	,[Name] VARCHAR(500) NULL
	,[AKA] VARCHAR(500) NULL
	,[City] VARCHAR(500) NULL
	,[State] VARCHAR(500) NULL
	,[Start] VARCHAR(500) NULL
	,[End] VARCHAR(500) NULL
	,[League] VARCHAR(500) NULL
	,[Notes] VARCHAR(500) NULL
)
GO

