CREATE TABLE [raw].[TeamMaster]
(
	[TeamID] VARCHAR(500) NULL
	,[League] VARCHAR(500) NULL
	,[City] VARCHAR(500) NULL
	,[Nickname] VARCHAR(500) NULL
	,[Start] VARCHAR(500) NULL
	,[End] VARCHAR(500) NULL
)
GO

