IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Event]') AND type in (N'U'))
DROP TABLE [dbo].[Event]

CREATE TABLE [dbo].[Event](
	[EventID] [bigint] IDENTITY(1,1) NOT NULL,
	[GameID] [bigint] NOT NULL,
	[EventNum] [int] NULL,
	[Inning] [int] NULL,
	[BattingTeam] [bit] NULL,
	[Outs] [int] NULL,
	[Balls] [int] NULL,
	[Strikes] [int] NULL,
	[PitchSequence] [varchar](max) NULL,
	[VisScore] [int] NULL,
	[HomeScore] [int] NULL,
	[Batter] [int] NULL,
	[BatterHand] [char](1) NULL,
	[ResBatter] [int] NULL,
	[ResBatterHand] [char](1) NULL,
	[Pitcher] [int] NULL,
	[PitcherHand] [char](1) NULL,
	[ResPitcher] [int] NULL,
	[ResPitcherHand] [char](1) NULL,
	[Catcher] [int] NULL,
	[FirstBase] [int] NULL,
	[SecondBase] [int] NULL,
	[ThirdBase] [int] NULL,
	[Shortstop] [int] NULL,
	[LeftField] [int] NULL,
	[CenterField] [int] NULL,
	[RightField] [int] NULL,
	[FirstRunner] [int] NULL,
	[SecondRunner] [int] NULL,
	[ThirdRunner] [int] NULL,
	[EventText] [varchar](max) NULL,
	[LeadoffFlag] [bit] NULL,
	[PinchHitFlag] [bit] NULL,
	[DefensivePosition] [int] NULL,
	[LineupPosition] [int] NULL,
	[EventType] [int] NULL,
	[BatterEventFlag] [bit] NULL,
	[ABFlag] [bit] NULL,
	[HitValue] [int] NULL,
	[SHFlag] [bit] NULL,
	[SFFlag] [bit] NULL,
	[OutsOnPlay] [int] NULL,
	[DoublePlayFlag] [bit] NULL,
	[TriplePlayFlag] [bit] NULL,
	[RBIOnPlay] [int] NULL,
	[WildPitchFlag] [bit] NULL,
	[PassedBallFlag] [bit] NULL,
	[FieldedBy] [int] NULL,
	[BattedBallType] [char](1) NULL,
	[BuntFlag] [bit] NULL,
	[FoulFlag] [bit] NULL,
	[HitLocation] [varchar](10) NULL,
	[NumErrors] [int] NULL,
	[ErrorPlayer1] [int] NULL,
	[ErrorType1] [char](1) NULL,
	[ErrorPlayer2] [int] NULL,
	[ErrorType2] [char](1) NULL,
	[ErrorPlayer3] [int] NULL,
	[ErrorType3] [char](1) NULL,
	[BatterDest] [int] NULL,
	[RunnerOn1stDest] [int] NULL,
	[RunnerOn2ndDest] [int] NULL,
	[RunnerOn3rdDest] [int] NULL,
	[PlayOnBatter] [varchar](50) NULL,
	[PlayOnRunnerOn1st] [varchar](50) NULL,
	[PlayOnRunnerOn2nd] [varchar](50) NULL,
	[PlayOnRunnerOn3rd] [varchar](50) NULL,
	[SBForRunnerOn1stFlag] [bit] NULL,
	[SBForRunnerOn2ndFlag] [bit] NULL,
	[SBForRunnerOn3rdFlag] [bit] NULL,
	[CSForRunnerOn1stFlag] [bit] NULL,
	[CSForRunnerOn2ndFlag] [bit] NULL,
	[CSForRunnerOn3rdFlag] [bit] NULL,
	[POForRunnerOn1stFlag] [bit] NULL,
	[POForRunnerOn2ndFlag] [bit] NULL,
	[POForRunnerOn3rdFlag] [bit] NULL,
	[ResponsiblePitcherForRunnerOn1st] [int] NULL,
	[ResponsiblePitcherForRunnerOn2nd] [int] NULL,
	[ResponsiblePitcherForRunnerOn3rd] [int] NULL,
	[NewGameFlag] [bit] NULL,
	[EndGameFlag] [bit] NULL,
	[PinchRunnerOn1st] [bit] NULL,
	[PinchRunnerOn2nd] [bit] NULL,
	[PinchRunnerOn3rd] [bit] NULL,
	[RunnerRemovedForPinchRunnerOn1st] [int] NULL,
	[RunnerRemovedForPinchRunnerOn1st2nd] [int] NULL,
	[RunnerRemovedForPinchRunnerOn1st3rd] [int] NULL,
	[BatterRemovedForPinchHitter] [int] NULL,
	[PositionOfBatterRemovedForPinchHitter] [int] NULL,
	[FielderWithFirstPutout] [int] NULL,
	[FielderWithSecondPutout] [int] NULL,
	[FielderWithThirdPutout] [int] NULL,
	[FielderWithFirstAssist] [int] NULL,
	[FielderWithSecondAssist] [int] NULL,
	[FielderWithThirdAssist] [int] NULL,
	[FielderWithFourthAssist] [int] NULL,
	[FielderWithFifthAssist] [int] NULL
 CONSTRAINT [pk_Event] PRIMARY KEY CLUSTERED 
(
	[EventID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
--  CONSTRAINT [ak_Event_RetroGameID_EventNum] UNIQUE NONCLUSTERED 
-- (
-- 	[GameID] ASC,
-- 	[EventNum] ASC
-- )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)
