USE [Retrosheet]
GO

/****** Object:  Table [raw].[Event]    Script Date: 9/25/2023 8:47:02 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[raw].[Event]') AND type in (N'U'))
DROP TABLE [raw].[Event]
GO

/****** Object:  Table [raw].[Event]    Script Date: 9/25/2023 8:47:02 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [raw].[Event](
	[GameID] [varchar](500) NOT NULL,
	[VisitingTeam] [varchar](500) NULL,
	[Inning] [varchar](500) NULL,
	[BattingTeam] [varchar](500) NULL,
	[Outs] [varchar](500) NULL,
	[Balls] [varchar](500) NULL,
	[Strikes] [varchar](500) NULL,
	[PitchSequence] [varchar](500) NULL,
	[VisScore] [varchar](500) NULL,
	[HomeScore] [varchar](500) NULL,
	[Batter] [varchar](500) NULL,
	[BatterHand] [varchar](500) NULL,
	[ResBatter] [varchar](500) NULL,
	[ResBatterHand] [varchar](500) NULL,
	[Pitcher] [varchar](500) NULL,
	[PitcherHand] [varchar](500) NULL,
	[ResPitcher] [varchar](500) NULL,
	[ResPitcherHand] [varchar](500) NULL,
	[Catcher] [varchar](500) NULL,
	[FirstBase] [varchar](500) NULL,
	[SecondBase] [varchar](500) NULL,
	[ThirdBase] [varchar](500) NULL,
	[Shortstop] [varchar](500) NULL,
	[LeftField] [varchar](500) NULL,
	[CenterField] [varchar](500) NULL,
	[RightField] [varchar](500) NULL,
	[FirstRunner] [varchar](500) NULL,
	[SecondRunner] [varchar](500) NULL,
	[ThirdRunner] [varchar](500) NULL,
	[EventText] [varchar](500) NULL,
	[LeadoffFlag] [varchar](500) NULL,
	[PinchHitFlag] [varchar](500) NULL,
	[DefensivePosition] [varchar](500) NULL,
	[LineupPosition] [varchar](500) NULL,
	[EventType] [varchar](500) NULL,
	[BatterEventFlag] [varchar](500) NULL,
	[ABFlag] [varchar](500) NULL,
	[HitValue] [varchar](500) NULL,
	[SHFlag] [varchar](500) NULL,
	[SFFlag] [varchar](500) NULL,
	[OutsOnPlay] [varchar](500) NULL,
	[DoublePlayFlag] [varchar](500) NULL,
	[TriplePlayFlag] [varchar](500) NULL,
	[RBIOnPlay] [varchar](500) NULL,
	[WildPitchFlag] [varchar](500) NULL,
	[PassedBallFlag] [varchar](500) NULL,
	[FieldedBy] [varchar](500) NULL,
	[BattedBallType] [varchar](500) NULL,
	[BuntFlag] [varchar](500) NULL,
	[FoulFlag] [varchar](500) NULL,
	[HitLocation] [varchar](500) NULL,
	[NumErrors] [varchar](500) NULL,
	[ErrorPlayer1] [varchar](500) NULL,
	[ErrorType1] [varchar](500) NULL,
	[ErrorPlayer2] [varchar](500) NULL,
	[ErrorType2] [varchar](500) NULL,
	[ErrorPlayer3] [varchar](500) NULL,
	[ErrorType3] [varchar](500) NULL,
	[BatterDest] [varchar](500) NULL,
	[RunnerOn1stDest] [varchar](500) NULL,
	[RunnerOn2ndDest] [varchar](500) NULL,
	[RunnerOn3rdDest] [varchar](500) NULL,
	[PlayOnBatter] [varchar](500) NULL,
	[PlayOnRunnerOn1st] [varchar](500) NULL,
	[PlayOnRunnerOn2nd] [varchar](500) NULL,
	[PlayOnRunnerOn3rd] [varchar](500) NULL,
	[SBForRunnerOn1stFlag] [varchar](500) NULL,
	[SBForRunnerOn2ndFlag] [varchar](500) NULL,
	[SBForRunnerOn3rdFlag] [varchar](500) NULL,
	[CSForRunnerOn1stFlag] [varchar](500) NULL,
	[CSForRunnerOn2ndFlag] [varchar](500) NULL,
	[CSForRunnerOn3rdFlag] [varchar](500) NULL,
	[POForRunnerOn1stFlag] [varchar](500) NULL,
	[POForRunnerOn2ndFlag] [varchar](500) NULL,
	[POForRunnerOn3rdFlag] [varchar](500) NULL,
	[ResponsiblePitcherForRunnerOn1st] [varchar](500) NULL,
	[ResponsiblePitcherForRunnerOn2nd] [varchar](500) NULL,
	[ResponsiblePitcherForRunnerOn3rd] [varchar](500) NULL,
	[NewGameFlag] [varchar](500) NULL,
	[EndGameFlag] [varchar](500) NULL,
	[PinchRunnerOn1st] [varchar](500) NULL,
	[PinchRunnerOn2nd] [varchar](500) NULL,
	[PinchRunnerOn3rd] [varchar](500) NULL,
	[RunnerRemovedForPinchRunnerOn1st] [varchar](500) NULL,
	[RunnerRemovedForPinchRunnerOn1st2nd] [varchar](500) NULL,
	[RunnerRemovedForPinchRunnerOn1st3rd] [varchar](500) NULL,
	[BatterRemovedForPinchHitter] [varchar](500) NULL,
	[PositionOfBatterRemovedForPinchHitter] [varchar](500) NULL,
	[FielderWithFirstPutout] [varchar](500) NULL,
	[FielderWithSecondPutout] [varchar](500) NULL,
	[FielderWithThirdPutout] [varchar](500) NULL,
	[FielderWithFirstAssist] [varchar](500) NULL,
	[FielderWithSecondAssist] [varchar](500) NULL,
	[FielderWithThirdAssist] [varchar](500) NULL,
	[FielderWithFourthAssist] [varchar](500) NULL,
	[FielderWithFifthAssist] [varchar](500) NULL,
	[EventNum] [varchar](500) NULL
) ON [PRIMARY]
GO


