USE [master]
GO

DROP DATABASE [Retrosheet]
GO

CREATE DATABASE [Retrosheet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Retrosheet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Retrosheet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Retrosheet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Retrosheet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Retrosheet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Retrosheet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Retrosheet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Retrosheet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Retrosheet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Retrosheet] SET ARITHABORT OFF 
GO

ALTER DATABASE [Retrosheet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Retrosheet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Retrosheet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Retrosheet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Retrosheet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Retrosheet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Retrosheet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Retrosheet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Retrosheet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Retrosheet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Retrosheet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Retrosheet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Retrosheet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Retrosheet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Retrosheet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Retrosheet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Retrosheet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Retrosheet] SET RECOVERY FULL 
GO

ALTER DATABASE [Retrosheet] SET  MULTI_USER 
GO

ALTER DATABASE [Retrosheet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Retrosheet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Retrosheet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Retrosheet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Retrosheet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Retrosheet] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Retrosheet] SET QUERY_STORE = ON
GO

ALTER DATABASE [Retrosheet] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Retrosheet] SET  READ_WRITE 
GO


