CREATE VIEW [dbo].[vw_Game]
AS
SELECT
	[GameID]
	,[ParkID]
	,[GameTypeID]
	,[RetroGameID]
	,[Date]
	,[GameNumber]
	,[DayOfWeek]
	,[StartTime]
	,[DHUsedFlag]
	,[DayNightFlag]
	,[VisitingTeam]
	,[HomeTeam]
	,[VisitorStartingPitcher]
	,[HomeStartingPitcher]
	,[HomePlateUmpire]
	,[FirstBaseUmpire]
	,[SecondBaseUmpire]
	,[ThirdBaseUmpire]
	,[LeftFieldUmpire]
	,[RightFieldUmpire]
	,[Attendance]
	,[HowScored]
	,[PitchesEntered]
	,[Temperature]
	,[WindDirection]
	,[WindSpeed]
	,[FieldCondition]
	,[Precipitation]
	,[Sky]
	,[TimeOfGame]
	,[NumberOfInnings]
	,[VisitorFinalScore]
	,[HomeFinalScore]
	,[VisitorHits]
	,[HomeHits]
	,[VisitorErrors]
	,[HomeErrors]
	,[VisitorLeftOnBase]
	,[HomeLeftOnBase]
	,[WinningPitcher]
	,[LosingPitcher]
	,[SaveFor]
	,[GWRBI]
	,[VisitorBatter1]
	,[VisitorPosition1]
	,[VisitorBatter2]
	,[VisitorPosition2]
	,[VisitorBatter3]
	,[VisitorPosition3]
	,[VisitorBatter4]
	,[VisitorPosition4]
	,[VisitorBatter5]
	,[VisitorPosition5]
	,[VisitorBatter6]
	,[VisitorPosition6]
	,[VisitorBatter7]
	,[VisitorPosition7]
	,[VisitorBatter8]
	,[VisitorPosition8]
	,[VisitorBatter9]
	,[VisitorPosition9]
	,[HomeBatter1]
	,[HomePosition1]
	,[HomeBatter2]
	,[HomePosition2]
	,[HomeBatter3]
	,[HomePosition3]
	,[HomeBatter4]
	,[HomePosition4]
	,[HomeBatter5]
	,[HomePosition5]
	,[HomeBatter6]
	,[HomePosition6]
	,[HomeBatter7]
	,[HomePosition7]
	,[HomeBatter8]
	,[HomePosition8]
	,[HomeBatter9]
	,[HomePosition9]
	,[VisitingFinisher]
	,[HomeFinisher]
	,[OfficialScorer]
	,CASE
		WHEN [VisitorFinalScore] = [HomeFinalScore] THEN 'TIE'
		WHEN [VisitorFinalScore] <> [HomeFinalScore] AND [WinningPitcher] IS NULL AND [LosingPitcher] IS NULL THEN 'FFT'
		WHEN [VisitorFinalScore] > [HomeFinalScore] THEN [VisitingTeam]
		WHEN [VisitorFinalScore] < [HomeFinalScore] THEN [HomeTeam]
		ELSE NULL
	END AS [WinningTeam]
	,CASE
		WHEN [VisitorFinalScore] = [HomeFinalScore] THEN 'TIE'
		WHEN [VisitorFinalScore] <> [HomeFinalScore] AND [WinningPitcher] IS NULL AND [LosingPitcher] IS NULL THEN 'FFT'
		WHEN [VisitorFinalScore] < [HomeFinalScore] THEN [VisitingTeam]
		WHEN [VisitorFinalScore] > [HomeFinalScore] THEN [HomeTeam]
		ELSE NULL
	END AS [LosingTeam]
FROM
	[dbo].[Game]